# 넘파이(umpy)

In [13]:
# 필요한 라이브러리 임포트
import numpy as np

## 넘파이 배열과 파이썬 리스트 비교

In [14]:
# 파이썬 리스트 자료 구조 데이터 생성
list_data = [1,2,3]
print(f'파이썬 리스트: {list_data}')

print('-'*80)

# 넘파이 배열 생성
array_data = np.array(list_data)
print(f'넘파이 배열로 변한 후 데이터: {array_data}')

파이썬 리스트: [1, 2, 3]
--------------------------------------------------------------------------------
넘파이 배열로 변한 후 데이터: [1 2 3]


In [15]:
# 파이썬 리스트와 넘파이 배열 차이점 확인

## 덧셈 연산

### 파이썬 리스트
result1 = list_data + list_data
print(f'파이썬 리스트에 대한 덧셈 연산의 결과: \n{result1}')

print('-'*80)

### 넘파이 배열
result2 = array_data + array_data
print(f'넘파이 배열에 대한 덧셈 연산의 결과: \n{result2}')

print('-'*80)

## 곱셈 연산

### 파이썬 리스트
result3 = []

for num in list_data:
    result3.append(num*3)

print(f'파이썬 리스트에 대한 곱셈 연산의 결과: \n{result3}')

파이썬 리스트에 대한 덧셈 연산의 결과: 
[1, 2, 3, 1, 2, 3]
--------------------------------------------------------------------------------
넘파이 배열에 대한 덧셈 연산의 결과: 
[2 4 6]
--------------------------------------------------------------------------------
파이썬 리스트에 대한 곱셈 연산의 결과: 
[3, 6, 9]


In [18]:
# 파이썬 리스트와 넘파이 배열 차이점 확인

## 덧셈 연산

### 파이썬 리스트
result1 = list_data + list_data
print(f'파이썬 리스트에 대한 덧셈 연산의 결과: \n{result1}')

print('-'*80)

### 넘파이 배열
result2 = array_data + array_data
print(f'넘파이 배열에 대한 덧셈 연산의 결과: \n{result2}')

print('-'*80)

## 곱셈 연산

### 파이썬 리스트
result3 = []

for num in list_data:
    result3.append(num*3)

print(f'파이썬 리스트에 대한 곱셈 연산의 결과: \n{result3}')

print('-'*80)

### 넘파이 배열
result4 = array_data * 3
print(f'넘파이 배열에 대한 곱셈 연산의 결과: \n{result4}')

print('-'*80)

## 통계 처리(평균 값 구하기)

### 파이썬 리스트
list_average = sum(list_data) / len(list_data)
print(f'파이썬 리스트에 대한 평균 값: {list_average}')

print('-'*80)

### 넘파이 배열
array_average = array_data.mean()
print(f'넘파이 배열에 대한 평균 값: {array_average}')

파이썬 리스트에 대한 덧셈 연산의 결과: 
[1, 2, 3, 1, 2, 3]
--------------------------------------------------------------------------------
넘파이 배열에 대한 덧셈 연산의 결과: 
[2 4 6]
--------------------------------------------------------------------------------
파이썬 리스트에 대한 곱셈 연산의 결과: 
[3, 6, 9]
--------------------------------------------------------------------------------
넘파이 배열에 대한 곱셈 연산의 결과: 
[3 6 9]
--------------------------------------------------------------------------------
파이썬 리스트에 대한 평균 값: 2.0
--------------------------------------------------------------------------------
넘파이 배열에 대한 평균 값: 2.0


In [19]:
# 대괄호가 중첩된 리스트 자료 구조 데이터 생성(조건: 성분 원소의 개수 동일)
list_data = [[1,2,3],[4,5,6],[7,8,9]] # 마지막 리스트의 길이를 다른 리스트와 동일하게 수정
print(f'대괄호가 중첩된 리스트 자료 구조 데이터 확인: \n{list_data}')

print('-'*80)

# 넘파이 배열로 변환 -> 엑셀과 같은 표(table: 행과 열) 구조 생성
array_data = np.array(list_data)
print(f'대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과: \n{array_data}')

대괄호가 중첩된 리스트 자료 구조 데이터 확인: 
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
--------------------------------------------------------------------------------
대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 2차원 배열 생성

In [21]:
# 대괄호가 중첩된 리스트 자료 구조 데이터 생성(조건: 성분 원소의 개수 동일)
list_data = [[1,2,3],[4,5,6]] # 마지막 리스트의 길이를 다른 리스트와 동일하게 수정
print(f'대괄호가 중첩된 리스트 자료 구조 데이터 확인: \n{list_data}')

print('-'*80)

# 넘파이 배열로 변환 -> 2차원 배열 -> 엑셀과 같은 표(table: 행과 열) 구조 생성
array_data = np.array(list_data)
print(f'대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과: \n{array_data}')

대괄호가 중첩된 리스트 자료 구조 데이터 확인: 
[[1, 2, 3], [4, 5, 6]]
--------------------------------------------------------------------------------
대괄호가 중첩된 리스트를 넘파이 배열로 변환한 결과: 
[[1 2 3]
 [4 5 6]]


## 인덱싱

In [ ]:
# 목표: 첫 번째 행, 첫 번째 열 -> 1 추출

## 1단계: 첫 번째 행 추출


# 넘파이 연습 문제

In [ ]:
# 문제1


In [ ]:
# 문제2

In [ ]:
# 문제3

In [ ]:
# 문제4

In [ ]:
# 문제5